"""Coverage analysis for parsing XML reports and computing module-level metrics."""

from __future__ import annotations

import json
import os
import xml.etree.ElementTree as ET
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------


@dataclass
class CoverageResult:
    """Coverage data for a single module or package.

    Attributes
    ----------
    module : str
        Module path (e.g. ``"database.db_service"``).
    total_lines : int
        Number of executable lines.
    covered_lines : int
        Number of lines executed by tests.
    coverage_pct : float
        Percentage of lines covered (0-100).
    missing_lines : list[int]
        Line numbers that were not executed.
    """

    module: str
    total_lines: int
    covered_lines: int
    coverage_pct: float
    missing_lines: list[int] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Analyzer
# ---------------------------------------------------------------------------


class CoverageAnalyzer:
    """Parse and analyse coverage XML reports (Cobertura format used by pytest-cov).

    Typical usage::

        analyzer = CoverageAnalyzer()
        results = analyzer.parse_coverage_report("coverage.xml")
        print(analyzer.get_overall_coverage())
        low = analyzer.get_low_coverage_modules(threshold=80.0)
    """

    def __init__(self, xml_path: str | None = None) -> None:
        """Initialise the analyser.

        Parameters
        ----------
        xml_path : str, optional
            Path to a Cobertura XML coverage report.  If provided, it is
            parsed immediately.
        """
        self._results: list[CoverageResult] = []
        if xml_path is not None:
            self._results = self.parse_coverage_report(xml_path)

    # -- Parsing -------------------------------------------------------------

    @staticmethod
    def parse_coverage_report(xml_path: str) -> list[CoverageResult]:
        """Parse a Cobertura XML coverage report.

        Parameters
        ----------
        xml_path : str
            Path to the XML file generated by ``pytest --cov-report=xml``.

        Returns
        -------
        list[CoverageResult]
            One entry per source file / module found in the report.

        Raises
        ------
        FileNotFoundError
            If *xml_path* does not exist.
        ValueError
            If the XML cannot be parsed as a Cobertura report.
        """
        path = Path(xml_path)
        if not path.is_file():
            raise FileNotFoundError(f"Coverage report not found: {xml_path}")

        try:
            tree = ET.parse(str(path))
        except ET.ParseError as exc:
            raise ValueError(f"Failed to parse XML: {exc}") from exc

        root = tree.getroot()
        results: list[CoverageResult] = []

        # Cobertura format: <coverage> <packages> <package> <classes> <class> ...
        for pkg in root.iter("package"):
            for cls in pkg.iter("class"):
                filename = cls.get("filename", "")
                if not filename:
                    continue

                # Convert file path to dotted module path.
                module = _filepath_to_module(filename)

                # Sum lines from <lines> children.
                total = 0
                covered = 0
                missing: list[int] = []
                for line_elem in cls.iter("line"):
                    hits = int(line_elem.get("hits", 0))
                    nr = int(line_elem.get("number", 0))
                    total += 1
                    if hits > 0:
                        covered += 1
                    else:
                        missing.append(nr)

                coverage_pct = (covered / total * 100.0) if total > 0 else 100.0
                results.append(
                    CoverageResult(
                        module=module,
                        total_lines=total,
                        covered_lines=covered,
                        coverage_pct=round(coverage_pct, 2),
                        missing_lines=sorted(missing),
                    )
                )

        # If no <package> blocks, fall back to line-level aggregation at root.
        if not results:
            results = _parse_flat_cobertura(root)

        return results

    # -- Queries -------------------------------------------------------------

    def get_module_coverage(self, module_name: str) -> CoverageResult:
        """Get coverage data for a specific module.

        Parameters
        ----------
        module_name : str
            Dotted module path (e.g. ``"database.db_service"``).

        Returns
        -------
        CoverageResult

        Raises
        ------
        ValueError
            If the module is not in the parsed results.
        """
        for r in self._results:
            if r.module == module_name:
                return r
        raise ValueError(f"Module {module_name!r} not found in coverage data")

    def get_overall_coverage(self) -> float:
        """Compute overall line-coverage across all modules.

        Returns
        -------
        float
            Coverage percentage (0-100).
        """
        total_lines = sum(r.total_lines for r in self._results)
        covered_lines = sum(r.covered_lines for r in self._results)
        if total_lines == 0:
            return 100.0
        return round((covered_lines / total_lines) * 100.0, 2)

    def get_low_coverage_modules(self, threshold: float = 80.0) -> list[CoverageResult]:
        """Return modules whose coverage is below *threshold*.

        Parameters
        ----------
        threshold : float
            Minimum acceptable coverage percentage (default 80.0).

        Returns
        -------
        list[CoverageResult]
            Modules sorted by coverage (ascending).
        """
        return sorted(
            [r for r in self._results if r.coverage_pct < threshold],
            key=lambda x: x.coverage_pct,
        )

    def get_uncovered_lines(self, module_name: str) -> list[int]:
        """Get uncovered line numbers for a specific module.

        Parameters
        ----------
        module_name : str

        Returns
        -------
        list[int]
        """
        return self.get_module_coverage(module_name).missing_lines

    def compare_coverage(
        self,
        baseline: list[CoverageResult],
        current: list[CoverageResult] | None = None,
    ) -> dict[str, Any]:
        """Compare two sets of coverage results (baseline vs current).

        Parameters
        ----------
        baseline : list[CoverageResult]
            Reference coverage data.
        current : list[CoverageResult], optional
            Current coverage data.  If not provided, uses the instance's
            parsed results.

        Returns
        -------
        dict
            Keys: ``"baseline_overall"``, ``"current_overall"``,
            ``"delta_pct"``, ``"improved"``, ``"regressed"``, ``"per_module"``.
        """
        current_data = current if current is not None else self._results

        baseline_map = {r.module: r for r in baseline}
        current_map = {r.module: r for r in current_data}

        baseline_overall = self._overall_from_list(baseline)
        current_overall = self._overall_from_list(current_data)
        delta = round(current_overall - baseline_overall, 2)

        per_module: dict[str, dict[str, float]] = {}
        improved: list[str] = []
        regressed: list[str] = []

        all_modules = set(baseline_map) | set(current_map)
        for mod in sorted(all_modules):
            b = baseline_map.get(mod)
            c = current_map.get(mod)
            b_cov = b.coverage_pct if b else 0.0
            c_cov = c.coverage_pct if c else 0.0
            diff = round(c_cov - b_cov, 2)
            per_module[mod] = {"baseline": b_cov, "current": c_cov, "delta": diff}
            if diff > 0:
                improved.append(mod)
            elif diff < 0:
                regressed.append(mod)

        return {
            "baseline_overall": baseline_overall,
            "current_overall": current_overall,
            "delta_pct": delta,
            "improved": improved,
            "regressed": regressed,
            "per_module": per_module,
        }

    @staticmethod
    def generate_summary(results: list[CoverageResult]) -> str:
        """Produce a human-readable summary string of coverage results.

        Parameters
        ----------
        results : list[CoverageResult]

        Returns
        -------
        str
        """
        if not results:
            return "No coverage data available."

        total_lines = sum(r.total_lines for r in results)
        covered_lines = sum(r.covered_lines for r in results)
        overall = (covered_lines / total_lines * 100.0) if total_lines > 0 else 100.0

        lines = [
            "=== Coverage Summary ===",
            f"  Overall: {overall:.2f}% ({covered_lines}/{total_lines} lines)",
            f"  Modules: {len(results)}",
            "",
            "  Per Module:",
        ]

        for r in sorted(results, key=lambda x: x.coverage_pct):
            lines.append(f"    {r.module:40s} {r.coverage_pct:6.2f}%  ({r.covered_lines:4d}/{r.total_lines})")

        return "\n".join(lines)

    # -- Calculation helpers -------------------------------------------------

    @staticmethod
    def calculate_statement_coverage(visited: int, total: int) -> float:
        """Calculate statement (line) coverage as a percentage.

        Parameters
        ----------
        visited : int
            Number of executed statements.
        total : int
            Total executable statements.

        Returns
        -------
        float
            0-100 percentage.
        """
        if total <= 0:
            return 100.0
        return round((visited / total) * 100.0, 2)

    @staticmethod
    def calculate_branch_coverage(covered: int, total: int) -> float:
        """Calculate branch coverage as a percentage.

        Parameters
        ----------
        covered : int
            Number of covered branches.
        total : int
            Total branches.

        Returns
        -------
        float
            0-100 percentage.
        """
        if total <= 0:
            return 100.0
        return round((covered / total) * 100.0, 2)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _overall_from_list(results: list[CoverageResult]) -> float:
        total_lines = sum(r.total_lines for r in results)
        covered_lines = sum(r.covered_lines for r in results)
        if total_lines == 0:
            return 100.0
        return round((covered_lines / total_lines) * 100.0, 2)


# ---------------------------------------------------------------------------
# Module-level helpers
# ---------------------------------------------------------------------------


def _filepath_to_module(filepath: str) -> str:
    """Convert a filesystem path to a dotted Python module name.

    Handles both POSIX and Windows path separators.

    Parameters
    ----------
    filepath : str
        E.g. ``"src/database/db_service.py"`` or ``"src\\database\\db_service.py"``.

    Returns
    -------
    str
        Dotted module path (e.g. ``"database.db_service"``).
    """
    # Normalise separators and strip extension.
    normalised = filepath.replace("\\", "/")
    normalised = os.path.splitext(normalised)[0]

    # Remove leading ``src/``, ``app/``, or similar if present.
    parts = normalised.split("/")
    # Skip typical source roots.
    while parts and parts[0] in ("src", "app", "source", "lib", "project"):
        parts.pop(0)

    return ".".join(parts)


def _parse_flat_cobertura(root: ET.Element) -> list[CoverageResult]:
    """Fallback parser for Cobertura reports that use a flat ``<lines>`` layout.

    Parameters
    ----------
    root : ET.Element

    Returns
    -------
    list[CoverageResult]
    """
    results: list[CoverageResult] = []
    # Aggregate all <line> elements under the root.
    all_lines: list[tuple[int, int]] = []  # (line_number, hits)
    file_to_lines: dict[str, list[tuple[int, int]]] = {}

    for line in root.iter("line"):
        filename = line.get("source", "") or line.get("filename", "") or "unknown"
        nr = int(line.get("number", 0))
        hits = int(line.get("hits", 0))
        file_to_lines.setdefault(filename, []).append((nr, hits))

    for filename, lines in file_to_lines.items():
        module = _filepath_to_module(filename)
        total = len(lines)
        covered = sum(1 for _, h in lines if h > 0)
        missing = [nr for nr, h in lines if h == 0]
        coverage_pct = (covered / total * 100.0) if total > 0 else 100.0
        results.append(
            CoverageResult(
                module=module,
                total_lines=total,
                covered_lines=covered,
                coverage_pct=round(coverage_pct, 2),
                missing_lines=sorted(missing),
            )
        )
    return results
