"""initial_schema

Revision ID: 55bc52dfc0c9
Revises: 
Create Date: 2026-07-03 15:21:01.167556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from database.base import UUIDType


# revision identifiers, used by Alembic.
revision: str = '55bc52dfc0c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('project_uuid', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_points', sa.JSON(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('sentiment', sa.String(length=32), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=False),
    sa.Column('complexity', sa.String(length=32), nullable=False),
    sa.Column('readability_score', sa.Float(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('pain_points', sa.JSON(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uuid', UUIDType(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_analyses_is_deleted'), 'analyses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_analyses_project_uuid'), 'analyses', ['project_uuid'], unique=False)
    op.create_index(op.f('ix_analyses_uuid'), 'analyses', ['uuid'], unique=False)
    op.create_index(op.f('ix_analyses_version'), 'analyses', ['version'], unique=False)
    op.create_index(op.f('ix_analyses_video_id'), 'analyses', ['video_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('project_uuid', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_uuid', sa.String(length=36), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uuid', UUIDType(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_type'), 'audit_logs', ['actor_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_is_deleted'), 'audit_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_audit_logs_project_uuid'), 'audit_logs', ['project_uuid'], unique=False)
    op.create_index(op.f('ix_audit_logs_uuid'), 'audit_logs', ['uuid'], unique=False)
    op.create_index(op.f('ix_audit_logs_version'), 'audit_logs', ['version'], unique=False)
    op.create_table('drafts',
    sa.Column('project_uuid', sa.String(length=36), nullable=False),
    sa.Column('draft_number', sa.Integer(), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('reading_time_minutes', sa.Integer(), nullable=False),
    sa.Column('section_count', sa.Integer(), nullable=False),
    sa.Column('heading_count', sa.Integer(), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('table_count', sa.Integer(), nullable=False),
    sa.Column('code_block_count', sa.Integer(), nullable=False),
    sa.Column('link_count', sa.Integer(), nullable=False),
    sa.Column('editor_version', sa.String(length=32), nullable=False),
    sa.Column('toc', sa.JSON(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uuid', UUIDType(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_drafts_draft_number'), 'drafts', ['draft_number'], unique=False)
    op.create_index(op.f('ix_drafts_is_deleted'), 'drafts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_drafts_project_uuid'), 'drafts', ['project_uuid'], unique=False)
    op.create_index(op.f('ix_drafts_uuid'), 'drafts', ['uuid'], unique=False)
    op.create_index(op.f('ix_drafts_version'), 'drafts', ['version'], unique=False)
    op.create_table('exports',
    sa.Column('project_uuid', sa.String(length=36), nullable=False),
    sa.Column('export_format', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('export_version', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('export_metadata', sa.JSON(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uuid', UUIDType(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_exports_checksum'), 'exports', ['checksum'], unique=False)
    op.create_index(op.f('ix_exports_export_format'), 'exports', ['export_format'], unique=False)
    op.create_index(op.f('ix_exports_is_deleted'), 'exports', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_exports_project_uuid'), 'exports', ['project_uuid'], unique=False)
    op.create_index(op.f('ix_exports_uuid'), 'exports', ['uuid'], unique=False)
    op.create_index(op.f('ix_exports_version'), 'exports', ['version'], unique=False)
    op.create_table('knowledge_graphs',
    sa.Column('project_uuid', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('relationships', sa.JSON(), nullable=False),
    sa.Column('facts', sa.JSON(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('timeline', sa.JSON(), nullable=False),
    sa.Column('pain_points', sa.JSON(), nullable=False),
    sa.Column('solutions', sa.JSON(), nullable=False),
    sa.Column('quotes', sa.JSON(), nullable=False),
    sa.Column('definitions', sa.JSON(), nullable=False),
    sa.Column('clusters', sa.JSON(), nullable=False),
    sa.Column('statistics', sa.JSON(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uuid', UUIDType(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_knowledge_graphs_is_deleted'), 'knowledge_graphs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_knowledge_graphs_project_uuid'), 'knowledge_graphs', ['project_uuid'], unique=False)
    op.create_index(op.f('ix_knowledge_graphs_uuid'), 'knowledge_graphs', ['uuid'], unique=False)
    op.create_index(op.f('ix_knowledge_graphs_version'), 'knowledge_graphs', ['version'], unique=False)
    op.create_index(op.f('ix_knowledge_graphs_video_id'), 'knowledge_graphs', ['video_id'], unique=False)
    op.create_table('optimizations',
    sa.Column('project_uuid', sa.String(length=36), nullable=False),
    sa.Column('draft_uuid', sa.String(length=36), nullable=False),
    sa.Column('review_uuid', sa.String(length=36), nullable=False),
    sa.Column('original_draft', sa.Text(), nullable=False),
    sa.Column('optimized_draft', sa.Text(), nullable=False),
    sa.Column('changes_applied', sa.JSON(), nullable=False),
    sa.Column('score_improvements', sa.JSON(), nullable=False),
    sa.Column('pre_optimization_scores', sa.JSON(), nullable=False),
    sa.Column('post_optimization_scores', sa.JSON(), nullable=False),
    sa.Column('gates_passed', sa.JSON(), nullable=False),
    sa.Column('gates_failed', sa.JSON(), nullable=False),
    sa.Column('optimization_round', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uuid', UUIDType(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_optimizations_draft_uuid'), 'optimizations', ['draft_uuid'], unique=False)
    op.create_index(op.f('ix_optimizations_is_deleted'), 'optimizations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_optimizations_project_uuid'), 'optimizations', ['project_uuid'], unique=False)
    op.create_index(op.f('ix_optimizations_uuid'), 'optimizations', ['uuid'], unique=False)
    op.create_index(op.f('ix_optimizations_version'), 'optimizations', ['version'], unique=False)
    op.create_table('outlines',
    sa.Column('project_uuid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('title_variants', sa.JSON(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('hierarchy', sa.JSON(), nullable=False),
    sa.Column('planned_word_count', sa.Integer(), nullable=False),
    sa.Column('introduction_plan', sa.Text(), nullable=False),
    sa.Column('conclusion_plan', sa.Text(), nullable=False),
    sa.Column('cta_plan', sa.Text(), nullable=False),
    sa.Column('faq_plan', sa.JSON(), nullable=False),
    sa.Column('image_placeholders', sa.JSON(), nullable=False),
    sa.Column('table_plans', sa.JSON(), nullable=False),
    sa.Column('example_plans', sa.JSON(), nullable=False),
    sa.Column('keywords_per_section', sa.JSON(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uuid', UUIDType(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_outlines_is_deleted'), 'outlines', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_outlines_project_uuid'), 'outlines', ['project_uuid'], unique=False)
    op.create_index(op.f('ix_outlines_uuid'), 'outlines', ['uuid'], unique=False)
    op.create_index(op.f('ix_outlines_version'), 'outlines', ['version'], unique=False)
    op.create_table('pipeline_states',
    sa.Column('project_uuid', sa.String(length=36), nullable=False),
    sa.Column('current_stage', sa.String(length=64), nullable=False),
    sa.Column('completed_stages', sa.JSON(), nullable=False),
    sa.Column('pending_stages', sa.JSON(), nullable=False),
    sa.Column('failed_stages', sa.JSON(), nullable=False),
    sa.Column('skipped_stages', sa.JSON(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('checkpoint', sa.JSON(), nullable=False),
    sa.Column('resume_point', sa.JSON(), nullable=False),
    sa.Column('pipeline_data', sa.JSON(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('stage_order', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.String(length=64), nullable=True),
    sa.Column('completed_at', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uuid', UUIDType(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_pipeline_states_is_deleted'), 'pipeline_states', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_pipeline_states_project_uuid'), 'pipeline_states', ['project_uuid'], unique=True)
    op.create_index(op.f('ix_pipeline_states_uuid'), 'pipeline_states', ['uuid'], unique=False)
    op.create_index(op.f('ix_pipeline_states_version'), 'pipeline_states', ['version'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('short_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('thumbnail', sa.Text(), nullable=False),
    sa.Column('channel_title', sa.String(length=512), nullable=False),
    sa.Column('channel_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('folder_path', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('pipeline_state', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('statistics', sa.JSON(), nullable=False),
    sa.Column('checkpoints', sa.JSON(), nullable=False),
    sa.Column('artifacts', sa.JSON(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('stage_data', sa.JSON(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uuid', UUIDType(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_short_id'), 'projects', ['short_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_uuid'), 'projects', ['uuid'], unique=False)
    op.create_index(op.f('ix_projects_version'), 'projects', ['version'], unique=False)
    op.create_index(op.f('ix_projects_video_id'), 'projects', ['video_id'], unique=False)
    op.create_table('reviews',
    sa.Column('project_uuid', sa.String(length=36), nullable=False),
    sa.Column('draft_uuid', sa.String(length=36), nullable=False),
    sa.Column('grammar_score', sa.Float(), nullable=False),
    sa.Column('seo_score', sa.Float(), nullable=False),
    sa.Column('readability_score', sa.Float(), nullable=False),
    sa.Column('hallucination_score', sa.Float(), nullable=False),
    sa.Column('eeat_score', sa.Float(), nullable=False),
    sa.Column('accessibility_score', sa.Float(), nullable=False),
    sa.Column('duplication_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('publication_status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uuid', UUIDType(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_reviews_draft_uuid'), 'reviews', ['draft_uuid'], unique=False)
    op.create_index(op.f('ix_reviews_is_deleted'), 'reviews', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_reviews_project_uuid'), 'reviews', ['project_uuid'], unique=False)
    op.create_index(op.f('ix_reviews_uuid'), 'reviews', ['uuid'], unique=False)
    op.create_index(op.f('ix_reviews_version'), 'reviews', ['version'], unique=False)
    op.create_table('seo',
    sa.Column('project_uuid', sa.String(length=36), nullable=False),
    sa.Column('primary_keyword', sa.String(length=512), nullable=False),
    sa.Column('secondary_keywords', sa.JSON(), nullable=False),
    sa.Column('lsi_keywords', sa.JSON(), nullable=False),
    sa.Column('search_intent', sa.String(length=64), nullable=False),
    sa.Column('meta_title', sa.Text(), nullable=False),
    sa.Column('meta_description', sa.Text(), nullable=False),
    sa.Column('url_slug', sa.String(length=512), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('content_structure', sa.JSON(), nullable=False),
    sa.Column('faq_schema', sa.JSON(), nullable=False),
    sa.Column('schema_markup', sa.JSON(), nullable=False),
    sa.Column('featured_snippet_target', sa.Text(), nullable=False),
    sa.Column('internal_links', sa.JSON(), nullable=False),
    sa.Column('external_links', sa.JSON(), nullable=False),
    sa.Column('competitor_keywords', sa.JSON(), nullable=False),
    sa.Column('seo_score', sa.Float(), nullable=False),
    sa.Column('readability_score', sa.Float(), nullable=False),
    sa.Column('keyword_difficulty', sa.Float(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uuid', UUIDType(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_seo_is_deleted'), 'seo', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_seo_primary_keyword'), 'seo', ['primary_keyword'], unique=False)
    op.create_index(op.f('ix_seo_project_uuid'), 'seo', ['project_uuid'], unique=False)
    op.create_index(op.f('ix_seo_uuid'), 'seo', ['uuid'], unique=False)
    op.create_index(op.f('ix_seo_version'), 'seo', ['version'], unique=False)
    op.create_table('transcripts',
    sa.Column('project_uuid', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('plain_text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('segments', sa.JSON(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uuid', UUIDType(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_transcripts_is_deleted'), 'transcripts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_transcripts_language'), 'transcripts', ['language'], unique=False)
    op.create_index(op.f('ix_transcripts_project_uuid'), 'transcripts', ['project_uuid'], unique=False)
    op.create_index(op.f('ix_transcripts_uuid'), 'transcripts', ['uuid'], unique=False)
    op.create_index(op.f('ix_transcripts_version'), 'transcripts', ['version'], unique=False)
    op.create_index(op.f('ix_transcripts_video_id'), 'transcripts', ['video_id'], unique=False)
    op.create_table('versions',
    sa.Column('project_uuid', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_uuid', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('previous_version_uuid', sa.String(length=36), nullable=True),
    sa.Column('previous_version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('changed_fields', sa.JSON(), nullable=False),
    sa.Column('changed_by', sa.String(length=128), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=64), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uuid', UUIDType(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_versions_entity_type'), 'versions', ['entity_type'], unique=False)
    op.create_index(op.f('ix_versions_entity_uuid'), 'versions', ['entity_uuid'], unique=False)
    op.create_index(op.f('ix_versions_is_deleted'), 'versions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_versions_project_uuid'), 'versions', ['project_uuid'], unique=False)
    op.create_index(op.f('ix_versions_uuid'), 'versions', ['uuid'], unique=False)
    op.create_index(op.f('ix_versions_version'), 'versions', ['version'], unique=False)
    op.create_index(op.f('ix_versions_version_number'), 'versions', ['version_number'], unique=False)
    op.create_table('videos',
    sa.Column('project_uuid', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('channel_title', sa.String(length=512), nullable=False),
    sa.Column('channel_id', sa.String(length=128), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=False),
    sa.Column('published_at', sa.String(length=64), nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=False),
    sa.Column('like_count', sa.BigInteger(), nullable=False),
    sa.Column('comment_count', sa.BigInteger(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=256), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('raw_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uuid', UUIDType(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_videos_is_deleted'), 'videos', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_videos_project_uuid'), 'videos', ['project_uuid'], unique=False)
    op.create_index(op.f('ix_videos_uuid'), 'videos', ['uuid'], unique=False)
    op.create_index(op.f('ix_videos_version'), 'videos', ['version'], unique=False)
    op.create_index(op.f('ix_videos_video_id'), 'videos', ['video_id'], unique=False)
    op.create_table('sections',
    sa.Column('project_uuid', sa.String(length=36), nullable=False),
    sa.Column('project_uuid_fk', sa.String(length=36), nullable=True),
    sa.Column('heading', sa.Text(), nullable=False),
    sa.Column('heading_tag', sa.String(length=4), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_plain', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('validation_score', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.String(length=64), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=False),
    sa.Column('llm_model', sa.String(length=128), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=False),
    sa.Column('subsections', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uuid', UUIDType(), nullable=False),
    sa.ForeignKeyConstraint(['project_uuid_fk'], ['projects.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_sections_is_deleted'), 'sections', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sections_project_uuid'), 'sections', ['project_uuid'], unique=False)
    op.create_index(op.f('ix_sections_status'), 'sections', ['status'], unique=False)
    op.create_index(op.f('ix_sections_uuid'), 'sections', ['uuid'], unique=False)
    op.create_index(op.f('ix_sections_version'), 'sections', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sections_version'), table_name='sections')
    op.drop_index(op.f('ix_sections_uuid'), table_name='sections')
    op.drop_index(op.f('ix_sections_status'), table_name='sections')
    op.drop_index(op.f('ix_sections_project_uuid'), table_name='sections')
    op.drop_index(op.f('ix_sections_is_deleted'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_videos_video_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_version'), table_name='videos')
    op.drop_index(op.f('ix_videos_uuid'), table_name='videos')
    op.drop_index(op.f('ix_videos_project_uuid'), table_name='videos')
    op.drop_index(op.f('ix_videos_is_deleted'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_versions_version_number'), table_name='versions')
    op.drop_index(op.f('ix_versions_version'), table_name='versions')
    op.drop_index(op.f('ix_versions_uuid'), table_name='versions')
    op.drop_index(op.f('ix_versions_project_uuid'), table_name='versions')
    op.drop_index(op.f('ix_versions_is_deleted'), table_name='versions')
    op.drop_index(op.f('ix_versions_entity_uuid'), table_name='versions')
    op.drop_index(op.f('ix_versions_entity_type'), table_name='versions')
    op.drop_table('versions')
    op.drop_index(op.f('ix_transcripts_video_id'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_version'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_uuid'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_project_uuid'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_language'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_is_deleted'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_seo_version'), table_name='seo')
    op.drop_index(op.f('ix_seo_uuid'), table_name='seo')
    op.drop_index(op.f('ix_seo_project_uuid'), table_name='seo')
    op.drop_index(op.f('ix_seo_primary_keyword'), table_name='seo')
    op.drop_index(op.f('ix_seo_is_deleted'), table_name='seo')
    op.drop_table('seo')
    op.drop_index(op.f('ix_reviews_version'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_uuid'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_project_uuid'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_is_deleted'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_draft_uuid'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_projects_video_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_version'), table_name='projects')
    op.drop_index(op.f('ix_projects_uuid'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_short_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_deleted'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_pipeline_states_version'), table_name='pipeline_states')
    op.drop_index(op.f('ix_pipeline_states_uuid'), table_name='pipeline_states')
    op.drop_index(op.f('ix_pipeline_states_project_uuid'), table_name='pipeline_states')
    op.drop_index(op.f('ix_pipeline_states_is_deleted'), table_name='pipeline_states')
    op.drop_table('pipeline_states')
    op.drop_index(op.f('ix_outlines_version'), table_name='outlines')
    op.drop_index(op.f('ix_outlines_uuid'), table_name='outlines')
    op.drop_index(op.f('ix_outlines_project_uuid'), table_name='outlines')
    op.drop_index(op.f('ix_outlines_is_deleted'), table_name='outlines')
    op.drop_table('outlines')
    op.drop_index(op.f('ix_optimizations_version'), table_name='optimizations')
    op.drop_index(op.f('ix_optimizations_uuid'), table_name='optimizations')
    op.drop_index(op.f('ix_optimizations_project_uuid'), table_name='optimizations')
    op.drop_index(op.f('ix_optimizations_is_deleted'), table_name='optimizations')
    op.drop_index(op.f('ix_optimizations_draft_uuid'), table_name='optimizations')
    op.drop_table('optimizations')
    op.drop_index(op.f('ix_knowledge_graphs_video_id'), table_name='knowledge_graphs')
    op.drop_index(op.f('ix_knowledge_graphs_version'), table_name='knowledge_graphs')
    op.drop_index(op.f('ix_knowledge_graphs_uuid'), table_name='knowledge_graphs')
    op.drop_index(op.f('ix_knowledge_graphs_project_uuid'), table_name='knowledge_graphs')
    op.drop_index(op.f('ix_knowledge_graphs_is_deleted'), table_name='knowledge_graphs')
    op.drop_table('knowledge_graphs')
    op.drop_index(op.f('ix_exports_version'), table_name='exports')
    op.drop_index(op.f('ix_exports_uuid'), table_name='exports')
    op.drop_index(op.f('ix_exports_project_uuid'), table_name='exports')
    op.drop_index(op.f('ix_exports_is_deleted'), table_name='exports')
    op.drop_index(op.f('ix_exports_export_format'), table_name='exports')
    op.drop_index(op.f('ix_exports_checksum'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_drafts_version'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_uuid'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_project_uuid'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_is_deleted'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_draft_number'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_audit_logs_version'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_uuid'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_project_uuid'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_is_deleted'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_analyses_video_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_version'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_uuid'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_project_uuid'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_is_deleted'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
